export const GET_YT_MUSIC_DATA_REQUEST = "GET_YT_MUSIC_DATA_REQUEST"
export const GET_YT_MUSIC_DATA_SUCCESS = "GET_YT_MUSIC_DATA_SUCCESS"
export const GET_YT_MUSIC_DATA_FAILED = "GET_YT_MUSIC_DATA_FAILED"